on:
  workflow_call: {}

name: "Test"

env:
  ERL_AFLAGS: "-enable-feature all"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      otpVersion: "${{ steps.toolVersions.outputs.OTP_VERSION }}"
      rebarVersion: "${{ steps.toolVersions.outputs.REBAR_VERSION }}"
      elixirVersion: "${{ steps.toolVersions.outputs.ELIXIR_VERSION }}"

    steps:
      - uses: actions/checkout@v4
      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          OTP_VERSION="$(cat .tool-versions | grep erlang | cut -d' ' -f2-)"
          echo OTP: $OTP_VERSION
          echo "OTP_VERSION=${OTP_VERSION}" >> $GITHUB_OUTPUT

          REBAR_VERSION="$(cat .tool-versions | grep rebar | cut -d' ' -f2-)"
          echo Rebar: $REBAR_VERSION
          echo "REBAR_VERSION=${REBAR_VERSION}" >> $GITHUB_OUTPUT

          ELIXIR_VERSION="$(cat .tool-versions | grep elixir | cut -d' ' -f2-)"
          echo Rebar: $ELIXIR_VERSION
          echo "ELIXIR_VERSION=${ELIXIR_VERSION}" >> $GITHUB_OUTPUT

  rebar_format:
    name: rebar3 fmt

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: rebar_format-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            rebar_format-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: rebar3 fmt --check

  mix_format:
    name: mix format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: mix_format-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_format-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: mix_format-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_format-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: mix deps.get
      - run: mix format --check-formatted

  eunit:
    name: rebar3 eunit (${{ matrix.otp }})

    runs-on: ubuntu-latest

    needs: ["detectToolVersions"]

    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: "26.0"
            unstable: false
          - otp: "26.2.5"
            unstable: false
          - otp: "27.0"
            unstable: false
          - otp: "master"
            unstable: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: "${{ needs.detectToolVersions.outputs.rebarVersion }}"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: eunit-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            eunit-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: rebar3 eunit --cover --cover_export_name "eunit-${{ steps.setupBEAM.outputs.otp-version }}"
        continue-on-error: ${{ matrix.unstable }}
      - uses: actions/upload-artifact@v4
        if: "${{ matrix.otp == needs.detectToolVersions.outputs.otpVersion }}"
        with:
          name: eunit-coverage-${{ matrix.otp }}
          path: "_build/test/cover/eunit-${{ steps.setupBEAM.outputs.otp-version }}.coverdata"

  conformance:
    name: rebar3 ct (${{ matrix.otp }})

    runs-on: ubuntu-latest

    needs: ["detectToolVersions"]

    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: "26.0"
            unstable: false
          - otp: "26.2.5"
            unstable: false
          - otp: "27.0"
            unstable: false
          - otp: "master"
            unstable: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: "${{ needs.detectToolVersions.outputs.rebarVersion }}"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: ct-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            ct-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: rebar3 ct --cover --cover_export_name "ct-${{ steps.setupBEAM.outputs.otp-version }}"
        continue-on-error: ${{ matrix.unstable }}
      - uses: actions/upload-artifact@v4
        if: "${{ matrix.otp == needs.detectToolVersions.outputs.otpVersion }}"
        with:
          name: ct-coverage-${{ matrix.otp }}
          path: _build/test/cover/ct-${{ steps.setupBEAM.outputs.otp-version }}.coverdata

  mix_test:
    name: mix test (${{ matrix.elixir }})

    runs-on: ubuntu-latest

    needs: ["detectToolVersions"]

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.14.5"
            otp: "26.2.5"
            unstable: false
          - elixir: "1.15.8"
            otp: "26.2.5"
            unstable: false
          - elixir: "1.16.3"
            otp: "26.2.5"
            unstable: false
          - elixir: "1.17.0"
            otp: "27.0"
            unstable: false
          - elixir: "main"
            otp: "${{ needs.detectToolVersions.outputs.otpVersion }}"
            unstable: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          otp-version: "${{ matrix.otp }}"
          rebar3-version: "${{ needs.detectToolVersions.outputs.rebarVersion }}"
          elixir-version: "${{ matrix.elixir }}"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: mix_test-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_test-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: mix_test-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_test-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - run: mix test --cover --export-coverage "mix_test-${{ steps.setupBEAM.outputs.elixir-version }}"
        continue-on-error: ${{ matrix.unstable }}
      - uses: actions/upload-artifact@v4
        if: "${{ matrix.otp == needs.detectToolVersions.outputs.otpVersion }}"
        with:
          name: mix_test-coverage-${{ matrix.elixir }}
          path: cover/mix_test-${{ steps.setupBEAM.outputs.elixir-version }}.coverdata

  coverage:
    name: mix test.coverage

    runs-on: ubuntu-latest

    needs: ["eunit", "conformance", "mix_test"]

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: mix_test_coverage-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_test_coverage-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Unpack Artifacts
        run: |
          mkdir cover
          mv artifacts/*/*.coverdata cover
          rm -rf artifacts
      - uses: actions/cache@v4
        with:
          path: deps
          key: mix_test_coverage-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_test_coverage-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - run: mix test.coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cover

  coveralls:
    name: rebar3 coveralls send

    runs-on: ubuntu-latest

    needs: ["eunit", "conformance", "mix_test"]

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: cover-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            cover-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Unpack Artifacts
        run: |
          mkdir -p _build/test/cover/
          mv artifacts/*/*.coverdata _build/test/cover/
          rm -rf artifacts
      - run: rebar3 as test compile
      - run: rebar3 as test coveralls send
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: rebar3 lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: lint-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            lint-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: rebar3 lint

  credo:
    name: mix credo

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: credo-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            credo-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: credo-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            credo-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: mix deps.get
      - run: mix credo

  dialyxir:
    name: mix dialyzer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: dialyxir-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            dialyxir-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: dialyxir-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            dialyxir-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: mix deps.get
      - run: mix dialyzer

  dialyzer:
    name: rebar3 dialyzer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: dialyzer-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            dialyzer-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: rebar3 dialyzer

  hank:
    name: rebar3 hank

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: hank-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            hank-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-
      - run: rebar3 hank
